"""Cấp 8 – Thêm một số tính năng - soft delete todos

Revision ID: 77ff7354aa95
Revises: 5187361865bd
Create Date: 2026-03-09 16:58:25.383024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ff7354aa95'
down_revision: Union[str, Sequence[str], None] = '5187361865bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'deleted_at')
    # ### end Alembic commands ###
